name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-check:
    name: Lint & Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Syntax check all CLI files
        run: |
          node --check bin/insighta.js
          node --check lib/api.js
          node --check lib/credentials.js
          node --check lib/commands/auth.js
          node --check lib/commands/profiles.js

      - name: Verify CLI help works
        run: node bin/insighta.js --help
